export const contact = [
  {
    company: "attri",
    customer_type: "development",
    deleted: false,
    deleted_at: null,
    id: 1,
    image: null,
    initial_communication: "2023-06-29T05:44:50.445049",
    location: null,
    name: "attri test account",
    registered_email: "test@attri.ai.com",
    title: "Bot",
    updated_at: null,
    work_website: "www.attri.ai",
  },
  {
    company: "Gallagher",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 5,
    image: null,
    initial_communication: "2022-11-02T08:39:26",
    location: null,
    name: "Aaron Boggs",
    registered_email: "aaron_boggs@ajg.com",
    title: "Producer",
    updated_at: null,
    work_website: "http://www.ajg.com",
  },
  {
    company: "Aaron C. Lee Law Firm, PLLC",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 6,
    image: null,
    initial_communication: "2019-08-06T20:25:42",
    location: null,
    name: "Aaron C. Lee",
    registered_email: "aaron@acleelaw.com",
    title: "",
    updated_at: null,
    work_website: "http://www.acleelaw.com",
  },
  {
    company: "Robert Elliott Homes",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 7,
    image: null,
    initial_communication: "2017-03-28T14:44:45",
    location: null,
    name: "Aaron Sherman",
    registered_email: "aaron.sherman@stillwatercap.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "RE Journals",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 8,
    image: null,
    initial_communication: "2022-05-03T13:45:49",
    location: null,
    name: "Abby Lestin",
    registered_email: "abby.lestin@rejournals.com",
    title: "Event Coordinator",
    updated_at: null,
    work_website: "http://www.rejournals.com",
  },
  {
    company: "Ciarproperties",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 9,
    image: null,
    initial_communication: "2018-12-06T15:46:36",
    location: null,
    name: "Abigail Toj",
    registered_email: "atoj@ciarproperties.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "Triangle Engineering LLC",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 10,
    image: null,
    initial_communication: "2020-06-17T15:30:05",
    location: null,
    name: "Accounting",
    registered_email: "accounting@triangle-engr.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "Spiars Engineering",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 11,
    image: null,
    initial_communication: "2022-01-14T16:02:25",
    location: null,
    name: "Accounting",
    registered_email: "accounting@spiarsengineering.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "Ace Motel",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 12,
    image: null,
    initial_communication: "2023-04-21T03:34:47",
    location: null,
    name: "Ace Hotel Brooklyn",
    registered_email: "reservations.bk@acehotel.com",
    title: "",
    updated_at: null,
    work_website: "http://blog.acehotel.com",
  },
  {
    company: "Harbert Management Corporation",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 13,
    image: null,
    initial_communication: "2020-01-14T15:18:21",
    location: null,
    name: "Adam A. A. Krug",
    registered_email: "akrug@harbert.net",
    title: "Managing Director, US Real Estate",
    updated_at: null,
    work_website: "http://www.harbert.net",
  },
  {
    company: "",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 14,
    image: null,
    initial_communication: "2018-02-23T16:22:07",
    location: null,
    name: "Adam Bielecki",
    registered_email: "adambielecki@yahoo.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "Urban Land Institute",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 15,
    image: null,
    initial_communication: "2021-03-01T18:21:34",
    location: null,
    name: "Adam J. Smolyar",
    registered_email: "adam.j.smolyar@uli.org",
    title: "",
    updated_at: null,
    work_website: "http://www.theatreworksusa.org/giving_support.cfm",
  },
  {
    company: "Bisnow",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 16,
    image: null,
    initial_communication: "2020-10-20T14:30:22",
    location: null,
    name: "Adam Keith",
    registered_email: "adam.keith@bisnow.com",
    title: "Sales Manager, Dallas",
    updated_at: null,
    work_website: "http://www.bisnow.com",
  },
  {
    company: "A.Y. Strauss, LLC",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 17,
    image: null,
    initial_communication: "2018-01-29T18:07:45",
    location: null,
    name: "Adele Lee",
    registered_email: "alee@aystrauss.com",
    title: "",
    updated_at: null,
    work_website: "http://www.aystrauss.com",
  },
  {
    company: "Candace Rubin",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 18,
    image: null,
    initial_communication: "2020-12-18T21:15:01",
    location: null,
    name: "Adem Sumer",
    registered_email: "adem@candacerubin.com",
    title: "Real Estate Agent/Property Tax Consultant",
    updated_at: null,
    work_website: "",
  },
  {
    company: "Twin Creeks Golf Course",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 19,
    image: null,
    initial_communication: "2018-12-04T16:02:53",
    location: null,
    name: "Adina Ritter",
    registered_email: "aritter@arcisgolf.com",
    title: "General Manager",
    updated_at: null,
    work_website: "",
  },
  {
    company: "",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 20,
    image: null,
    initial_communication: "2018-12-27T17:31:44",
    location: null,
    name: "Adnan Shaikh",
    registered_email: "adnan@medicalsummitrcm.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "",
    customer_type: "Personal",
    deleted: false,
    deleted_at: null,
    id: 22,
    image: null,
    initial_communication: "2016-11-17T15:29:20",
    location: null,
    name: "Adriane Devereux",
    registered_email: "adriane.devereux@gmail.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
  {
    company: "",
    customer_type: "Potential Customer",
    deleted: false,
    deleted_at: null,
    id: 23,
    image: null,
    initial_communication: "2019-01-29T20:10:18",
    location: null,
    name: "Afshan Rajani",
    registered_email: "afshanrajani@yahoo.com",
    title: "Broker",
    updated_at: null,
    work_website: "",
  },
  {
    company: "Drinkag1",
    customer_type: "Vendor",
    deleted: false,
    deleted_at: null,
    id: 24,
    image: null,
    initial_communication: "2023-06-27T15:56:34",
    location: null,
    name: "AG1®",
    registered_email: "support@drinkag1.com",
    title: "",
    updated_at: null,
    work_website: "",
  },
];
