name: dev
on:
  push:
    branches:
      - cicd/dev

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: smartagentconsole
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: '#smart-agent-deployment'
  
jobs:

  build-image-and-push-to-acr:
    runs-on: ubuntu-20.04
    steps:

    # Init Slack Notification
    # - uses: act10ns/slack@v2.0.0
    #   with:
    #     status: starting
    #     config: .github/config/slack.yml
    #     channel: ${{ env.SLACK_CHANNEL }}
    #     message: Smart Agent FE deployment started...

    # Checkout Repository
    - uses: actions/checkout@master
    
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ env.REGISTRY_NAME }} 
        password: ${{ secrets.AZ_REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/smart-agent-fe:${{ github.sha }} -t ${{ env.REGISTRY_NAME }}.azurecr.io/smart-agent-fe:latest
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/smart-agent-fe:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/smart-agent-fe:latest

    # Send job status to slack
    # - uses: act10ns/slack@v2.0.0
    #   with:
    #     status: ${{ job.status }}
    #     config: .github/config/slack.yml
    #     steps: ${{ toJson(steps) }}
    #     channel: ${{ env.SLACK_CHANNEL }}
    #   if: always()